import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print (arr)

newarr = arr.reshape(-1)
print("newarr = arr.reshape(-1)")
print(newarr)
newarr = arr.reshape(3,2)
print("newarr = arr.reshape(3,2)")
print(newarr)
newarr = arr.reshape(1,6)
print("newarr = arr.reshape(1,6)")
print(newarr)
newarr = arr.reshape(6,1)
print("newarr = arr.reshape(6,1)")
print(newarr)
newarr = arr.reshape(6)
print("newarr = arr.reshape(6)")
print(newarr)
print (newarr.base)
# ~ newarr = arr.reshape(1)
# ~ print(newarr)
